### ISSUE TITLE
Documentation isn't upto the mark

### ISSUE THREAD

**Issue by pnijhara** [AMU-Code-Squad/food-up#28]
- Update Readme.md

**Comment by pnijhara** [comment]
Can also add a point that after a PR merge contributor can add his/her name in https://amu-code-squad.github.io

**Comment by Lordhacker756** [comment]
Hello, I'm looking forward to contributing to open source, and I would like to work on improving the documentation, can you please assign this to me😄

**Comment by pnijhara** [comment]
@Lordhacker756 go ahead!

**Comment by Lordhacker756** [comment]
Thank You Very Much!

**Comment by Lordhacker756** [comment]
@pnijhara I've opened a pull request for the work done, please review it😄

**Comment by Lordhacker756** [comment]
@pnijhara I've created a PR on amu code squad's github.io, please review it, Thanks!😄
