### ISSUE TITLE
Add suitable license to the project

### ISSUE THREAD

**Issue by pnijhara** [AMU-Code-Squad/food-up#40]
@husainhz7 what do you think, which license is suitable for the project?

**Comment by husainhz7** [comment]
Since this is a learning project, you can set it to MIT. I find it the most permissive license.

**Comment by pnijhara** [comment]
I agree with you that it a learning project. However, this project can go further as an open-source project for others to learn also. Will MIT works in that case too?

**Comment by husainhz7** [comment]
If we want to impose open-source on projects using our code (copy-left) we can use GPL v3. I think its better to remove that pressure using MIT. During my internship, my manager asked me to be vary of copy-left licences code. Had I included that our code would have been open-sourced!

**Comment by pnijhara** [comment]
So GPL v3 is it?
Keeping the project open-source will attract a lot of newcomers to work on a simple project like this.

**Comment by husainhz7** [comment]
An MIT licence gives more freedom for people to use our code in every situation. How will using GPL attract more newcomers?

**Comment by pnijhara** [comment]
Oh no! I was just asking!
Will add MIT license.
