### ISSUE TITLE
Improve code quality

### ISSUE THREAD

**Issue by pnijhara** [AMU-Code-Squad/food-up#42]
- The current codebase has many irrelevant arguments in the callback functions which are never called. They can either removed or replaced with `_` or prefixed with `_`. 
- There are several dependencies which are called but never used and thus can be removed.
- Improve naming convention (prefer camelCase)

**Comment by Mingos1** [comment]
Hi there, I would like to work on this issue. 

It's been a few months since this issue was opened, are there new things that need to be improved upon within the codebase?

**Comment by pnijhara** [comment]
Sure go ahead!

**Comment by pnijhara** [comment]
@Mingos1, there were no more changes made after this issue. You can go with the codebase. Feel free to ping if you find any issue. Moreover, you can fix these code quality issues by taking help from [DeepSource](https://deepsource.io)

**Comment by Mingos1** [comment]
Unfortunately, I will have to pull back from working on this issue since it's out of my scope. 

Thank you for the opportunity and help!
