### ISSUE TITLE
PORT is defined as 3000 in readme.md but 3001 in app.js

### ISSUE THREAD

**Issue by iamAravindks** [AMU-Code-Squad/food-up#71]
https://github.com/AMU-Code-Squad/food-up/blob/89c8bca917f8d4cbf0b2911ccff3beb99adb230c/app.js#L71
the PORT is defined as 3000 in the readme.md but it says 3001 in app.js .

**Comment by iamAravindks** [comment]
is this project is alive ?

**Comment by khushi2706** [comment]
issue solved in #74
